# Generated by Django 5.0.7 on 2025-10-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_condition',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
