# Generated by Django 5.0.7 on 2025-10-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_experience_years_user_license_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
    ]
