# Generated by Django 5.0.7 on 2025-11-02 07:12

from django.db import migrations, models


def add_is_verified_if_missing(apps, schema_editor):
    """Safely add the is_verified column only if it doesn't already exist.

    This avoids errors on databases where the column may have been added manually
    or by a previous migration.
    """
    connection = schema_editor.connection
    User = apps.get_model('accounts', 'User')
    table = User._meta.db_table

    with connection.cursor() as cursor:
        try:
            description = connection.introspection.get_table_description(cursor, table)
            existing = {col.name for col in description}
        except Exception:
            existing = set()

    if 'is_verified' in existing:
        return

    # Add the column with a default of False
    field = models.BooleanField(default=False)
    field.set_attributes_from_name('is_verified')
    schema_editor.add_field(User, field)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(add_is_verified_if_missing, migrations.RunPython.noop),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
