# Generated by Django 5.0.7 on 2025-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_personal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
