# Generated by Django 5.0.7 on 2025-11-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_is_verified_alter_user_emergency_contact'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='is_verified',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
