# Generated by Django 5.0.7 on 2025-11-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('medications', '0006_compliancefollowup_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General Care Note'), ('handoff', 'Caregiver Handoff'), ('observation', 'Clinical Observation'), ('alert', 'Important Alert'), ('medication', 'Medication Related'), ('behavior', 'Behavior Note'), ('emergency', 'Emergency Contact/Info')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin important notes to the top')),
                ('is_archived', models.BooleanField(default=False, help_text='Archive old/resolved notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_care_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='care_notes', to=settings.AUTH_USER_MODEL)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_notes', to='appointments.appointment')),
                ('related_medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_notes', to='medications.medication')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareNoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_note_comments', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='carenotes.carenote')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareNoteRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='carenotes.carenote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_care_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddIndex(
            model_name='carenote',
            index=models.Index(fields=['patient', '-created_at'], name='carenotes_c_patient_18041d_idx'),
        ),
        migrations.AddIndex(
            model_name='carenote',
            index=models.Index(fields=['note_type', '-created_at'], name='carenotes_c_note_ty_d66bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='carenote',
            index=models.Index(fields=['priority'], name='carenotes_c_priorit_286277_idx'),
        ),
        migrations.AddIndex(
            model_name='carenote',
            index=models.Index(fields=['-is_pinned', '-created_at'], name='carenotes_c_is_pinn_81b95f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carenoteread',
            unique_together={('note', 'user')},
        ),
    ]
