# Generated by Django 5.0.7 on 2025-11-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carenotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carenote',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
