# Generated by Django 5.0.7 on 2025-10-11 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.IntegerField(default=0)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'start_time'],
                'indexes': [models.Index(fields=['caregiver', 'date'], name='timesheet_t_caregiv_e84e74_idx'), models.Index(fields=['status'], name='timesheet_t_status_d31984_idx')],
            },
        ),
    ]
