# Generated by Django 5.0.7 on 2025-11-20 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['caregiver', 'day_of_week'], name='availabilit_caregiv_8ff3f2_idx'), models.Index(fields=['is_available'], name='availabilit_is_avai_f060d3_idx')],
                'unique_together': {('caregiver', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='SpecificDateAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='appointments.appointment')),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='specific_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Specific date availabilities',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['caregiver', 'date'], name='availabilit_caregiv_ff366d_idx'), models.Index(fields=['is_available'], name='availabilit_is_avai_d0a40e_idx')],
            },
        ),
    ]
