# Generated by Django 5.0.7 on 2025-10-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_medication_end_date_medication_refill_threshold_and_more'),
        ('medications', '0002_medication_tracking'),
    ]

    operations = [
    ]
