# Generated by Django 5.0.7 on 2025-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_compliance_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancefollowup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
