# Generated by Django 5.0.7 on 2025-10-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('medications', '0005_alter_compliancefollowup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancefollowup',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='appointments.appointment'),
        ),
    ]
