# Generated by Django 5.0.7 on 2025-10-19 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=15)),
                ('amount', models.PositiveIntegerField(help_text='Amount in KES')),
                ('command_id', models.CharField(default='BusinessPayment', max_length=64)),
                ('remarks', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=16)),
                ('safaricom_conversation_id', models.CharField(blank=True, max_length=128)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=128)),
                ('result_code', models.CharField(blank=True, max_length=16)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
