# Generated by Django 5.0.7 on 2025-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='hour', max_length=50)),
                ('urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
