# Generated by Django 5.0.7 on 2025-10-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestsapp', '0002_add_relations_to_carerequest'),
        ('requestsapp', '0002_doctorrequest'),
    ]

    operations = [
    ]
