# Generated by Django 5.0.7 on 2025-10-14 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsapp', '0004_delete_doctorrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting this doctor')),
                ('symptoms', models.TextField(blank=True, help_text='Current symptoms or conditions')),
                ('preferred_date', models.DateField(blank=True, help_text='Preferred first appointment date', null=True)),
                ('preferred_time', models.TimeField(blank=True, help_text='Preferred first appointment time', null=True)),
                ('urgent', models.BooleanField(default=False, help_text='Is this request urgent?')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from patient')),
                ('doctor_notes', models.TextField(blank=True, help_text='Notes from doctor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Doctor being requested', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_requests_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient requesting doctor assignment', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
