# Generated by Django 5.0.7 on 2025-10-10 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_vitalreading_notes_vitalreading_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalreading',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
